### Ideal Gas Law is an equation of state, which describes the correlation between the pressure, volume & temperature of a hypothetical ideal gas.

### The following set of class and functions serves as the generator and interface management system of the GUI that was created with QT designer.
### The calculations can be performed by importing the igl_app_formulae.py file.
### Using number of moles n and ideal gas constant R from Version 1 of part 1.

# Created by: PyQt5 UI code generator 5.15.11 & QT Designer
# -*- coding: utf-8 -*-
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtCore import *
from PyQt5.QtGui import *
from PyQt5.QtWidgets import *
from igl_app_gui_formulae import Pressure, Volume, Temperature

### ------- GUI CONFIGURATION ------- ###
class Ui_igl_app_gui(object):
    # WINDOW ELEMENTS CONFIGURATION - SIZE & LAYOUT
    def setupUi(self, igl_app_gui):
        # Main settings
        igl_app_gui.setObjectName("igl_app_gui")
        igl_app_gui.resize(350, 345)
        igl_app_gui.setMaximumSize(QtCore.QSize(350, 345))
        self.centralwidget = QtWidgets.QWidget(igl_app_gui)
        self.centralwidget.setObjectName("centralwidget")
        
        # Title & Formula
        self.mainLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.mainLayout.setObjectName("mainLayout")
        self.titleLayout = QtWidgets.QVBoxLayout()
        self.titleLayout.setObjectName("titleLayout")
        self.title_label = QtWidgets.QLabel(self.centralwidget)
        self.title_label.setAlignment(QtCore.Qt.AlignCenter)
        self.title_label.setObjectName("title_label")
        self.titleLayout.addWidget(self.title_label, 0, QtCore.Qt.AlignHCenter)
        self.formula_label = QtWidgets.QLabel(self.centralwidget)
        self.formula_label.setAlignment(QtCore.Qt.AlignCenter)
        self.formula_label.setObjectName("formula_label")
        self.titleLayout.addWidget(self.formula_label, 0, QtCore.Qt.AlignHCenter)
        self.mainLayout.addLayout(self.titleLayout)
        
        # Quantities Grid - Layout
        self.inputGrid = QtWidgets.QGridLayout()
        self.inputGrid.setObjectName("inputGrid")
        self.quantity_label = QtWidgets.QLabel(self.centralwidget)
        self.quantity_label.setObjectName("quantity_label")
        self.inputGrid.addWidget(self.quantity_label, 0, 0, 1, 1)
        self.quantities_selector = QtWidgets.QComboBox(self.centralwidget)
        self.quantities_selector.setObjectName("quantities_selector")
        self.quantities_selector.addItem("")
        self.quantities_selector.addItem("")
        self.quantities_selector.addItem("")
        self.quantities_selector.addItem("")
        self.inputGrid.addWidget(self.quantities_selector, 0, 1, 1, 1)
            # Moles Input Field
        self.moles_label = QtWidgets.QLabel(self.centralwidget)
        self.moles_label.setObjectName("moles_label")
        self.inputGrid.addWidget(self.moles_label, 1, 0, 1, 1)
        self.moles_input = QtWidgets.QSpinBox(self.centralwidget)
        self.moles_input.setMinimum(0)
        self.moles_input.setMaximum(100)
        self.moles_input.setProperty("value", 0)
        self.moles_input.setObjectName("moles_input")
        self.moles_input.setEnabled(False)
        self.inputGrid.addWidget(self.moles_input, 1, 1, 1, 1)
            # Pressure (P) Input field
        self.pressure_label = QtWidgets.QLabel(self.centralwidget)
        self.pressure_label.setObjectName("pressure_label")
        self.inputGrid.addWidget(self.pressure_label, 2, 0, 1, 1)
        self.pressure_input = QtWidgets.QLineEdit(self.centralwidget)
        self.pressure_input.setObjectName("pressure_input")
        self.pressure_input.setEnabled(False)
        self.inputGrid.addWidget(self.pressure_input, 2, 1, 1, 1)
            # Volume (V) Input field
        self.volume_label = QtWidgets.QLabel(self.centralwidget)
        self.volume_label.setObjectName("volume_label")
        self.inputGrid.addWidget(self.volume_label, 3, 0, 1, 1)
        self.volume_input = QtWidgets.QLineEdit(self.centralwidget)
        self.volume_input.setObjectName("volume_input")
        self.volume_input.setEnabled(False)
        self.inputGrid.addWidget(self.volume_input, 3, 1, 1, 1)
            # Temperature (T) Input field
        self.temperature_label = QtWidgets.QLabel(self.centralwidget)
        self.temperature_label.setObjectName("temperature_label")
        self.inputGrid.addWidget(self.temperature_label, 4, 0, 1, 1)
        self.temperature_input = QtWidgets.QLineEdit(self.centralwidget)
        self.temperature_input.setObjectName("temperature_input")
        self.temperature_input.setEnabled(False)
        self.inputGrid.addWidget(self.temperature_input, 4, 1, 1, 1)
            # ! Numerical format validation !
        validator = QDoubleValidator()
        validator.setBottom(0) # No negatives are allowed
        validator.setNotation(QDoubleValidator.StandardNotation)
        
        self.moles_input.cleanText()
        self.pressure_input.setValidator(validator)
        self.volume_input.setValidator(validator)
        self.temperature_input.setValidator(validator)
            # Grid implementation
        self.mainLayout.addLayout(self.inputGrid)
        
        # Buttons (Calculate & Clear) - Layout
        self.buttonLayout = QtWidgets.QHBoxLayout()
        self.buttonLayout.setObjectName("buttonLayout")
        self.button_calculate = QtWidgets.QPushButton(self.centralwidget)
        self.button_calculate.setObjectName("button_calculate")
        self.buttonLayout.addWidget(self.button_calculate)
        self.button_clear = QtWidgets.QPushButton(self.centralwidget)
        self.button_clear.setObjectName("button_clear")
        self.buttonLayout.addWidget(self.button_clear)
        self.mainLayout.addLayout(self.buttonLayout)
        
        # Result Field - Layout
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.result_label = QtWidgets.QLabel(self.centralwidget)
        self.result_label.setTextFormat(QtCore.Qt.RichText)
        self.result_label.setAlignment(QtCore.Qt.AlignCenter)
        self.result_label.setObjectName("result_label")
        self.verticalLayout.addWidget(self.result_label)
        self.result_output = QtWidgets.QLineEdit(self.centralwidget)
        self.result_output.setReadOnly(True)
        self.result_output.setObjectName("result_output")
        self.verticalLayout.addWidget(self.result_output)
        self.mainLayout.addLayout(self.verticalLayout)
        
        igl_app_gui.setCentralWidget(self.centralwidget)

        self.retranslateUi(igl_app_gui)
        QtCore.QMetaObject.connectSlotsByName(igl_app_gui)

    ### ------- ELEMENT TITLES & OTHER TEXT ------- ###
    def retranslateUi(self, igl_app_gui):
        _translate = QtCore.QCoreApplication.translate
        # Title Section
        igl_app_gui.setWindowTitle(_translate("igl_app_gui", "Ideal Gas Law - Calculator App"))
        self.title_label.setText(_translate("igl_app_gui", "<h1><u>Ideal Gas Law</u></h1>"))
        self.formula_label.setText(_translate("igl_app_gui", "<h3><i>PV = n*R*T</i></h3>"))
        # Quantities Section
        self.quantity_label.setText(_translate("igl_app_gui", "<b>Quantity to Calculate</b>"))
        self.quantities_selector.setItemText(0, _translate("igl_app_gui", "Select your quantity"))
        self.quantities_selector.setItemText(1, _translate("igl_app_gui", "Pressure (P)"))
        self.quantities_selector.setItemText(2, _translate("igl_app_gui", "Volume (V)"))
        self.quantities_selector.setItemText(3, _translate("igl_app_gui", "Temperature (T)"))
        self.quantities_selector.currentIndexChanged.connect(self.update_input_fields)
        self.moles_label.setText(_translate("igl_app_gui", "<b>Moles</b> (n)"))
        self.pressure_label.setText(_translate("igl_app_gui", "<b>Pressure</b> (Pa)"))
        self.volume_label.setText(_translate("igl_app_gui", "<b>Volume</b> (m³)"))
        self.temperature_label.setText(_translate("igl_app_gui", "<b>Temperature</b> (K)"))
        # Quantities Placeholders - Disabled by Default
        self.pressure_input.setPlaceholderText(_translate("igl_app_gui", "Disabled"))
        self.volume_input.setPlaceholderText(_translate("igl_app_gui", "Disabled"))
        self.temperature_input.setPlaceholderText(_translate("igl_app_gui", "Disabled"))
        # Buttons
        self.button_calculate.setText(_translate("igl_app_gui", "Calculate"))
        self.button_calculate.clicked.connect(self.run_calculation)
        self.button_clear.setText(_translate("igl_app_gui", "Clear"))
        self.button_clear.clicked.connect(self.clear_fields)
        # Result
        self.result_label.setText(_translate("igl_app_gui", "<h3><u>RESULT</u></h3>"))
        self.result_output.setPlaceholderText(_translate("igl_app_gui", "The result will be displayed here."))
    
    ### ------- DISABLE CALCULATED QUANTITY (BASED ON COMBOBOX SELECTOR) ------- ###
    def update_input_fields(self):
        quantity = self.quantities_selector.currentText()
        
        # By default, all quantities are disabled (Check "Quantities Grid" above).
        if quantity == "Select your quantity":
            self.moles_input.setEnabled(False)
            self.pressure_input.setEnabled(False)
            self.volume_input.setEnabled(False)
            self.temperature_input.setEnabled(False)
            self.moles_input.setProperty("value", 0)
            self.pressure_input.clear()
            self.volume_input.clear()
            self.temperature_input.clear()
            self.result_output.clear()
            self.pressure_input.setPlaceholderText("Disabled")
            self.volume_input.setPlaceholderText("Disabled")
            self.temperature_input.setPlaceholderText("Disabled")
        # Quantity Selector - User's Choice
        elif quantity == "Pressure (P)":
            self.moles_input.setEnabled(True)
            self.volume_input.setEnabled(True)
            self.temperature_input.setEnabled(True)
            self.moles_input.setProperty("value", 0)
            self.pressure_input.clear()
            self.volume_input.clear()
            self.temperature_input.clear()
            self.result_output.clear()
            self.pressure_input.setPlaceholderText("Disabled")
            self.volume_input.setPlaceholderText("e.g. 0.01 m³")
            self.temperature_input.setPlaceholderText("e.g. 300 K")
        elif quantity == "Volume (V)":
            self.moles_input.setEnabled(True)
            self.pressure_input.setEnabled(True)
            self.temperature_input.setEnabled(True)
            self.moles_input.setProperty("value", 0)
            self.pressure_input.clear()
            self.volume_input.clear()
            self.temperature_input.clear()
            self.result_output.clear()
            self.pressure_input.setPlaceholderText("e.g. 100 Pa")
            self.volume_input.setPlaceholderText("Disabled")
            self.temperature_input.setPlaceholderText("e.g. 300 K")
        elif quantity == "Temperature (T)":
            self.moles_input.setEnabled(True)
            self.pressure_input.setEnabled(True)
            self.volume_input.setEnabled(True)
            self.moles_input.setProperty("value", 0)
            self.pressure_input.clear()
            self.volume_input.clear()
            self.temperature_input.clear()
            self.result_output.clear()
            self.pressure_input.setPlaceholderText("e.g. 100 Pa")
            self.volume_input.setPlaceholderText("e.g. 0.01 m³")
            self.temperature_input.setPlaceholderText("Disabled")  
    
    ### ------- CALCULATION BUTTON FUNCTIONALITY ------- ###
    def run_calculation(self):
        quantity = self.quantities_selector.currentText()

        try:
            n = self.moles_input.value()
            P = float(self.pressure_input.text()) if self.pressure_input.text() else None
            V = float(self.volume_input.text()) if self.volume_input.text() else None
            T = float(self.temperature_input.text()) if self.temperature_input.text() else None
                
            if quantity == "Pressure (P)":
                if V is None or T is None:
                    raise ValueError("Please provide Volume and Temperature!")
                result = Pressure(n,V,T)
                self.result_output.setText(f"{result:.2f} Pa")
                
            elif quantity == "Volume (V)":
                if P is None or T is None:
                    raise ValueError("Please provide Pressure and Temperature!")
                result = Volume(n,P,T)
                self.result_output.setText(f"{result:.2f} m³")
                    
            elif quantity == "Temperature (T)":
                if P is None or V is None:
                    raise ValueError("Please provide Pressure and Volume!")
                result = Temperature(n,P,V)
                self.result_output.setText(f"{result:.2f} K")
                
        except ValueError as e:
            QMessageBox.warning(None, "Input Error", str(e))
        except Exception:
            QMessageBox.warning(None, "Error", "Unexpected Error: Please check your inputs!")

    ### ------- CLEAR BUTTON FUNCTIONALITY ------- ###
    def clear_fields(self):
        self.pressure_input.clear()
        self.volume_input.clear()
        self.temperature_input.clear()
        self.moles_input.setValue(1)
        self.result_output.clear()
               
# GUI EXECUTION - The GUI will appear using IDLE.  
if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_igl_app_gui()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec())